{
 "title": "Loki log explorer",
 "description": "Dashboard to explore logs per system",
 "tags": [ "loki" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error|critical|crash" },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count of: $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Show log messages that match search pattern",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", container=~\"$container\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Total count of log messages",
   "type": "piechart",
   "description": "Summarize log messages per file",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\"})[$__interval])) by (container)",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\"",
   "type": "piechart",
   "description": "Summarize log files that match searchable pattern",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", container=~\"$container\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (container)",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "description": "Percentage of log messages that match searchable pattern",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", container=~\"$container\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({namespace=\"$namespace\", container=~\"$container\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" per log file",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", container=~\"$container\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (container)",
     "legendFormat": "{{filename}}"
    }
   ]
  }
 ]
}