{
 "title": "MatchdayProLogs",
 "tags": [ "loki" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs Volume vs time by container",
   "type": "timeseries",
   "description": "Show volume versus time in selected *time range*, filtering by *namespace*, *container* and *filter*",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(container) (count_over_time({namespace=\"$namespace\", container=~\"$container\"} |~ `(?i)$filter` | logfmt [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs volume by container",
   "type": "bargauge",
   "description": "Show total volume in selected *time range*, filtering by *namespace* and *filter*",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (count_over_time({namespace=\"$namespace\"} |~ `(?i)$filter` | logfmt | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Errors for container=$container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "All logs",
   "type": "stat",
   "description": "All log lines in *time range*",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", container=~\"$container\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs by severity",
   "type": "piechart",
   "description": "Logs by *PriorityName* as severity level. Can be empty since this field is not always filled up",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(priorityName) (count_over_time({namespace=\"$namespace\"} |= `` | json | unpack | priorityName =~ `(?P<pname>.+)` | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Errors/Warning/Critical/Crash by container",
   "type": "gauge",
   "description": "Show all containers that present case insensitive *error|err|crash|warn|warning|critical*",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (count_over_time({namespace=\"$namespace\"} |~ `(?i)error|crash|warn|warning|critical` | logfmt | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "ERROR",
   "type": "stat",
   "description": "case insensitive *error*|*err* in *time range*",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", container=~\"$container\"} |~ `(?i)error|err` [$__interval]))"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "stat",
   "description": "case insensitive *warning*|*warn* in *time range*",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", container=~\"$container\"} |~ `(?i)warn|warning` [$__interval]))"
    }
   ]
  },
  {
   "title": "CRITICAL",
   "type": "stat",
   "description": "case insensitive *critical* in *time range*",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", container=~\"$container\"} |~ `(?i)critical` [$__interval]))"
    }
   ]
  },
  {
   "title": "CRASH",
   "type": "stat",
   "description": "case insensitive *crash* in *time range*",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", container=~\"$container\"} |~ `(?i)crash` [$__interval]))"
    }
   ]
  },
  { "title": "Drill Down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Raw Logs",
   "type": "logs",
   "description": "Show log lines in selected *time range*, filtering by *namespace*, *container* and *filter*",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", container=~\"$container\"} |~ `(?i)$filter` | logfmt | __error__=``"
    }
   ]
  }
 ]
}